site_name: OpenCVE Documentation

repo_name: opencve/opencve-docs
repo_url: https://github.com/opencve/opencve-docs
edit_uri: ""

theme:
  logo: images/logo.png
  favicon: images/favicon.png
  name: 'material'
  palette:
    accent: blue

extra_css:
  - css/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.superfences

nav:
  - Home: 'index.md'
  - Deployment & Setup: 'deployment.md'
  - Knowledge Base (KB): 'kb.md'
  - v1:
    - Home: 'v1/index.md'
    - Installation:
      - Manual: 'v1/installation/manual.md'
      - Docker: 'v1/installation/docker.md'
    - How it Works: 'v1/how-it-works.md'
    - Commands: 'v1/commands.md'
    - Admin: 'v1/admin.md'
    - Settings: 'v1/settings.md'
    - API:
      - Introduction: 'v1/api/index.md'
      - /account: 'v1/api/account.md'
      - /cve: 'v1/api/cve.md'
      - /cwe: 'v1/api/cwe.md'
      - /vendors: 'v1/api/vendors.md'
      - /products: 'v1/api/products.md'
      - /reports: 'v1/api/reports.md'
      - /alerts: 'v1/api/alerts.md'
    - FAQ: 'v1/faq.md'
